### ISSUE TITLE
[Docs] Documentation Todo 

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy#8]
- [ ] Add documentation for the Discord module
- [x] Add documentation for the Config module
- [ ] Detail more the MySQL storage component
- [ ] Work on some good examples

I'll try helping out as much as possible,
Much love,
- Ghast
